In [1]:
import numpy as np 
import pandas as pd

In [2]:
def rmspe(y_true, y_pred):
    return np.sqrt(np.mean(np.square((y_true - y_pred) / y_true)))

In [3]:
train = pd.read_pickle('input/train_248.pkl')
test = pd.read_pickle('input/test_247.pkl')

# valid
valid_pred_lgb1 = pd.read_csv('outputs/valid_pred_lgb1.csv')
valid_pred_lgb2 = pd.read_csv('outputs/valid_pred_lgb2.csv')
valid_pred_nn1 = pd.read_csv('outputs/nn1_valid_pred.csv')
valid_pred_nn2 = pd.read_csv('outputs/nn2_valid_pred.csv')
valid_pred_tabnet = pd.read_csv('outputs/valid_pred_tabnet.csv')

# load predict data...

In [4]:
valid_pred_lgb1 = np.array(valid_pred_lgb1).reshape(-1)
valid_pred_lgb2 = np.array(valid_pred_lgb2).reshape(-1)

valid_pred_nn1 = np.array(valid_pred_nn1).reshape(-1)
valid_pred_nn2 = np.array(valid_pred_nn2).reshape(-1)

valid_pred_tabnet = np.array(valid_pred_tabnet).reshape(-1)

In [5]:
valid_pred_lgb1, valid_pred_lgb2, valid_pred_nn1, valid_pred_nn2, valid_pred_tabnet

(array([0.00416712, 0.00153504, 0.00214595, ..., 0.00313415, 0.00451236,
        0.00206082]),
 array([0.00431598, 0.00163058, 0.00222032, ..., 0.00320257, 0.00465226,
        0.00206749]),
 array([0.00366505, 0.0014547 , 0.00219503, ..., 0.00327135, 0.00471491,
        0.00199602]),
 array([0.00370796, 0.00146185, 0.0021736 , ..., 0.00322349, 0.00478484,
        0.0019784 ]),
 array([0.00395556, 0.00151696, 0.00234024, ..., 0.00327264, 0.00481214,
        0.00210196]))

In [6]:
# 测试比例
valid_pred = 0.2*(0.55*valid_pred_lgb1+0.45*valid_pred_lgb2) + 0.3*(0.5*valid_pred_nn1+0.5*valid_pred_nn2) + 0.5*valid_pred_tabnet
rmspe(np.array(train['target']), valid_pred)

0.2035501074109606

In [7]:
# 根据比例，赋值给test_pred..
# final_pred = 0.325*(0.6*predictions_lgb1+0.4*predictions_lgb2) + 0.375*(0.3*test_predictions_nn1+0.7*test_predictions_nn2) + 0.3*test_tabnet_preds
# final_pred

In [8]:
# test[target_name] = final_pred

# # score = round(rmspe(y_true = train[target_name].values, y_pred = train[pred_name].values),5)
# # print('RMSPE {}: {} - Folds: {}'.format(model_name, score, scores_folds[model_name]))

# display(test[['row_id', target_name]].head(3))
# test[['row_id', target_name]].to_csv('outputs/submission.csv',index = False)
# #test[['row_id', target_name]].to_csv('submission.csv',index = False)
# #kmeans N=5 [0.2101, 0.21399, 0.20923, 0.21398, 0.21175]